
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqbhtvgpylngscpuqasb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYmh0dmdweWxuZ3NjcHVxYXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTkxNDIsImV4cCI6MjA2MTc5NTE0Mn0.SgGj0eo4k7R0jhjBqnUuZvq2Qh6b9saTIzFx1XJKrTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
